### ISSUE TITLE
Suggestion: Add functionality to automatically clear cache when necessary.

### ISSUE THREAD

**Issue by jordanmack** [nervosnetwork/ckb-cli#290]
It would be beneficial to automatically clear the ckb-cli cache when it is detected that the active ckb instance differs from what was cached. 

As seen below, I had performed a full reset on the dev chain, but the wallet command was still returning information from the deleted chain.

```
CKB> rpc get_tip_block_number
507
CKB> wallet get-live-cells --lock-hash 0x5094cc3c0e78c997c9c4ed53cdba443739c83cbca9e2487ff3b17b821e61dad9 --limit 1
current_capacity: 2009.88422898 (CKB)
current_count: 1
live_cells:
  - capacity: 2009.88422898 (CKB)
    data_bytes: 0
    index:
      output_index: 0
      tx_index: 0
    lock_hash: 0x5094cc3c0e78c997c9c4ed53cdba443739c83cbca9e2487ff3b17b821e61dad9
    mature: false
    number: 12
    tx_hash: 0x29190882a3975e35bad66ebd57d34f65a135635b250c2ad69ab8014291330b86
    tx_index: 0
    type_hashes: ~
total_capacity: 62565512.94281988 (CKB)
total_count: 55235
```
