### ISSUE TITLE
Is it possible to send CKB from derived addresses?

### ISSUE THREAD

**Issue by jhartzell42** [nervosnetwork/ckb-cli#299]
If I have a file-based key account, and want to receive funds from someone, best practices say that I should give the other person an extended address:

```
CKB> account list
- "#": 0
  address:
    testnet: ckt1qyqfer8qr6hnjy9ckxxr9f87cdln6d0cgpqs8pwkc9
  lock_arg: 0x9c8ce01eaf3910b8b18c32a4fec37f3d35f84041

CKB> account extended-address --lock-arg 0x9c8ce01eaf3910b8b18c32a4fec37f3d35f84041 --path "m/44'/309'/0'/0/1"
Password:
address:
  testnet: ckt1qyqw87pst0w6vuqumzqsq4z5q7fzxgjtlkuq2xlvfs
lock_arg: 0xe3f8305bdda6701cd881005454079223224bfdb8
```

At this point, I give the derived address to the person who is sending me the funds. They do so, and I can verify that in the CLI as well:

```
CKB> wallet get-capacity --address ckt1qyqw87pst0w6vuqumzqsq4z5q7fzxgjtlkuq2xlvfs
total: 499.999 (CKB)
```

Now how do I spend from this account? One thing I've tried, that didn't work, includes specifying the specific derived account the funds are in. It appears that there is no record kept of the matching private key to the address I derived before:

```
CKB> wallet transfer --from-account ckt1qyqw87pst0w6vuqumzqsq4z5q7fzxgjtlkuq2xlvfs --to-address ckt1qyqygts28uuvmaqd5nvrzm3qc03zlrymje4sypz5un --capacity 499.998 --tx-fee 0.001
Password:
Account not found: e3f8305bdda6701cd881005454079223224bfdb8

CKB> wallet transfer --from-account 0xe3f8305bdda6701cd881005454079223224bfdb8 --to-address ckt1qyqygts28uuvmaqd5nvrzm3qc03zlrymje4sypz5un --capacity 499.998 --tx-fee 0.001
Password:
Account not found: e3f8305bdda6701cd881005454079223224bfdb8

```
If I try to instead provide the root/main account, I only have access to the funds in that account directly:

```
CKB> wallet get-capacity --lock-arg 0x9c8ce01eaf3910b8b18c32a4fec37f3d35f84041
total: 150.0 (CKB)

CKB> wallet transfer --from-account 0x9c8ce01eaf3910b8b18c32a4fec37f3d35f84041 --to-address ckt1qyqygts28uuvmaqd5nvrzm3qc03zlrymje4sypz5un --capacity 499.998 --tx-fee 0.001
Password:
Capacity(mature) not enough: ckt1qyqfer8qr6hnjy9ckxxr9f87cdln6d0cgpqs8pwkc9 => 15000000000
```

How can I sign things with the extended-address private key, so that I can spend CKB sent to me on an extended address? Is there a way to get `wallet transfer` to derive extended private keys?

Thank you in advance for your help and consideration!
