### ISSUE TITLE
Messages cannot be signed by extended addresses, only accounts

### ISSUE THREAD

**Issue by mikereinhart** [nervosnetwork/ckb-cli#301]
Tested on 856af0b8a29043f36f06d4f5be7744a293ae24d2

Messages can be signed by accounts, but it seems they cannot be signed by extended addresses.

```
CKB> account list
...
- "#": 3
  address:
    mainnet: ckb1qyqzylky4l68z9gqc8wu0zfjvcj8ujjlzfks0eyj6p
    testnet: ckt1qyqzylky4l68z9gqc8wu0zfjvcj8ujjlzfksju6dka
  lock_arg: 0x227ec4aff4711500c1ddc7893266247e4a5f126d
  lock_hash: 0x7e7142b84f567039b7fc1a7186bee9f4be30efdca46e3e8c4f8efb058040135d
```
I then derive an address from this account
```
CKB> account extended-address --lock-arg 0x227ec4aff4711500c1ddc7893266247e4a5f126d --path "m/44'/309'/0'/0/0"
Password:
address:
  mainnet: ckb1qyq8ma3xf7x7unls4a9l0uq8huz8h2k8j4jqdurvwf
  testnet: ckt1qyq8ma3xf7x7unls4a9l0uq8huz8h2k8j4jqseanz4
lock_arg: 0x7df6264f8dee4ff0af4bf7f007bf047baac79564
```
I can sign a message with the account's sighash:
```
CKB> util sign-message --from-account ckt1qyqzylky4l68z9gqc8wu0zfjvcj8ujjlzfksju6dka --message 435cf99e6d25fb179264edfdeb11261f406be3c7350d9031d07ec10f1695b393
Password:
recoverable: false
signature: 0xa7fb4d4390058cd84f8fa9face08f4c6ed035b0a2ba1f19699625deb072cc97c42a69685951512ac0bdba71f6870fa293ce40d507bea3078e952c6fbc71d903a
```
or its lock-arg:
```
CKB> util sign-message --from-account 0x227ec4aff4711500c1ddc7893266247e4a5f126d --message 435cf99e6d25fb179264edfdeb11261f406be3c7350d9031d07ec10f1695b393
Password:
recoverable: false
signature: 0xa7fb4d4390058cd84f8fa9face08f4c6ed035b0a2ba1f19699625deb072cc97c42a69685951512ac0bdba71f6870fa293ce40d507bea3078e952c6fbc71d903a
```
But signing a message with an extended address does not seem to work:
```
CKB> util sign-message --from-account ckt1qyq8ma3xf7x7unls4a9l0uq8huz8h2k8j4jqseanz4 --message 435cf99e6d25fb179264edfdeb11261f406be3c7350d9031d07ec10f1695b393
Password:
Account not found: 7df6264f8dee4ff0af4bf7f007bf047baac79564
```
And neither does the extended address' lock-arg:
```
CKB> util sign-message --from-account 0x7df6264f8dee4ff0af4bf7f007bf047baac79564 --message 435cf99e6d25fb179264edfdeb11261f406be3c7350d9031d07ec10f1695b393
Password:
Account not found: 7df6264f8dee4ff0af4bf7f007bf047baac79564
```

Thanks in advance for your help!
