### ISSUE TITLE
Using the lock-arg of a keyfile extended-address in a transfer reports a Ledger error

### ISSUE THREAD

**Issue by mikereinhart** [nervosnetwork/ckb-cli#343]
I'm using:

- CKB-CLI: 0.35.0
- Ledger Plugin: v0.2.0

Recognizing that the proper way to construct a `wallet transfer` command that uses capacity from derived addresses is to use the root account's lock-arg as the `--from-account`, if you use the lock-arg of an extended-address you will see a Ledger error even though key from local file storage is used. This has proven confusing at times while testing Ledger features and comparing results with keys from local file storage.

### Reproduction Steps

Here are my addresses and their balances
```
CKB> account list
...
- "#": 3
  address:
    mainnet: ckb1qyq9x0frsy76j2ynf2taay4ssy85x76vm4kslrwglp
    testnet: ckt1qyq9x0frsy76j2ynf2taay4ssy85x76vm4kszxshna
  has_ckb_root: false
  lock_arg: 0x533d23813da928934a97de92b0810f437b4cdd6d
  lock_hash: 0x8438647a667fcd57dd31f259f751e7e5af9924c8d4a8bc56b5b685e2586d2217
  source: Local File System

CKB> account extended-address --lock-arg 0x533d23813da928934a97de92b0810f437b4cdd6d --path "m/44'/309'/0'/0/0"
Password:
address:
  mainnet: ckb1qyqzjk834kaayapnzfq9ejxudpc2fscfruzqpv9xkq
  testnet: ckt1qyqzjk834kaayapnzfq9ejxudpc2fscfruzqufme6u
lock_arg: 0x2958f1adbbd2743312405cc8dc6870a4c3091f04

CKB> wallet get-capacity --address ckt1qyqzylky4l68z9gqc8wu0zfjvcj8ujjlzfksju6dka
total: 3000.0 (CKB)

CKB> wallet get-capacity --address ckt1qyqzjk834kaayapnzfq9ejxudpc2fscfruzqufme6u
total: 3000.0 (CKB)

CKB> account extended-address --lock-arg 0x533d23813da928934a97de92b0810f437b4cdd6d --path "m/44'/309'/0'/1/0"
Password:
address:
  mainnet: ckb1qyq2pxlsn0nmzx7s3f2pua3x5aj3teqxwkmqmk585n
  testnet: ckt1qyq2pxlsn0nmzx7s3f2pua3x5aj3teqxwkmqxn2cc0
lock_arg: 0xa09bf09be7b11bd08a541e7626a76515e40675b6
```

**Actual Result**: Attempting to transfer from the extended-address lock-arg reports a Ledger error, even though the accounts in question are all stored in the local file system:
```
CKB> wallet transfer --from-account 0x2958f1adbbd2743312405cc8dc6870a4c3091f04 --to-address ckt1qyqg64fqws0sdgrz2s7da2dzrlpq6plw9xcq2e8e5l --capacity 1000 --tx-fee 0.001 --derive-change-address ckt1qyq2pxlsn0nmzx7s3f2pua3x5aj3teqxwkmqxn2cc0
Ledger account for lock_arg: H160 ( [ 0x29, 0x58, 0xf1, 0xad, 0xbb, 0xd2, 0x74, 0x33, 0x12, 0x40, 0x5c, 0xc8, 0xdc, 0x68, 0x70, 0xa4, 0xc3, 0x09, 0x1f, 0x04 ] ) not found
```

**Expected Result**: The error message would reference that it cannot find the lock-arg in a way that is inclusive of all the local file system.

As you might expect, using the lock-arg of the root account works!
```
CKB> wallet transfer --from-account 0x533d23813da928934a97de92b0810f437b4cdd6d --to-address ckt1qyqg64fqws0sdgrz2s7da2dzrlpq6plw9xcq2e8e5l --capacity 1000 --tx-fee 0.001 --derive-change-address ckt1qyq2pxlsn0nmzx7s3f2pua3x5aj3teqxwkmqxn2cc0
Password:
Password:
0xa2a4a24cfcffd8634612cf6793099cb64ea895fb1b87f2e33ce68541de42e9b1
```
