### ISSUE TITLE
`rpc get_transaction` output lacks fields such as `fee`

### ISSUE THREAD

**Issue by sunchengzhu** [nervosnetwork/ckb-cli#615]
### Missing fields:
fee, min_replace_fee, time_added_to_pool

### Version
ckb-cli 1.12.0 (278c7be 2024-09-20)

### Current Behavior
Querying a [pending transaction](https://pudge.explorer.nervos.org/en/transaction/list?tab=pending) (just to populate these fields that lack values,  **not necessarily requiring a pending transaction**).
#### ckb-cli
```
tx_hash="0xb2ad556c3539eecf94c5231abbe19664bf24b18c7170b10d95033f1522d80d74"
```
input: 
``` bash
export API_URL=https://testnet.ckbapp.dev
./ckb-cli rpc get_transaction --hash $tx_hash
```
output: 
``` yaml
cycles: 1768901
transaction:
  cell_deps:
    - dep_type: code
      out_point:
        index: 1
        tx_hash: 0x8ed481459e4d5906b2089d2b516c30b369fd3af5ebc1cded93dd17d28db1f73b
    - dep_type: dep_group
      out_point:
        index: 0
        tx_hash: 0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37
  hash: 0xb2ad556c3539eecf94c5231abbe19664bf24b18c7170b10d95033f1522d80d74
  header_deps: []
  inputs:
    - previous_output:
        index: 0
        tx_hash: 0xc7d90668e58c2252545cf06cbd760a2281da92432a541596a689f02d379b7826
      since: 0x0 (absolute block(0))
    - previous_output:
        index: 1
        tx_hash: 0xfae7c29232265063da649242ce382cff662738354d1258aa8712acfe5e742f49
      since: 0x0 (absolute block(0))
  outputs:
    - capacity: "442.0"
      lock:
        args: 0xce5d9dfb0aa6e080a26be07a3cc7772d01b15882
        code_hash: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 (sighash)
        hash_type: type
      type:
        args: 0x1c483ff12bb834ed5607d22b17b3d1e7fbb43dfb8997c12cc7b4643db181ca40
        code_hash: 0xf03989dd98974d7a6cbe0a73cdbc4b4839a048a120f6cffd73db935b73c357a5
        hash_type: type
    - capacity: "89752.36347644"
      lock:
        args: 0xce5d9dfb0aa6e080a26be07a3cc7772d01b15882
        code_hash: 0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8 (sighash)
        hash_type: type
      type: ~
  outputs_data:
    - 0x4f7261636c6543656c6c32010000080000002a0100000c0000009b0000008f00000018000000200000004000000041000000490000000400000057425443cdc9073cbe050000000000000000000000000000000000000000000000000000080dda381592010000420000003078636331346162613034663062303361356466356566326363326131363366663334633335383633666264363563643133376165646530666234303334366636368f00000018000000200000004000000041000000490000000400000057434b42f76b180000000000000000000000000000000000000000000000000000000000080dda38159201000042000000307831373261663738313730353530656430383633383738656132623130396662616364333961666133326533306639666266353665313331336439623263613063
    - 0x
  version: 0
  witnesses:
    - 0x5500000010000000550000005500000041000000284be4b5f8f6530048e71b96d8becf64dd5c23873f59027a88ec13ca57912c607f909dbfa59b74d1955c8dab415f872f7cbd4a4b659af1bd059fa8184259179b00
tx_status:
  block_hash: ~
  block_number: ~
  reason: ~
  status: pending
  tx_index: ~
```

#### rpc

request:
``` bash
curl -sS -X POST -H "Content-Type: application/json" -d @- https://testnet.ckbapp.dev <<EOF | jq
{
  "id": 1,
  "jsonrpc": "2.0",
  "method": "get_transaction",
  "params": ["$tx_hash"]
}
EOF
```

response: 
``` json
{
  "jsonrpc": "2.0",
  "result": {
    "cycles": "0x1afdc5",
    "fee": "0x764",
    "min_replace_fee": "0xcef",
    "time_added_to_pool": "0x1921538e17c",
    "transaction": {
      "cell_deps": [
        {
          "dep_type": "code",
          "out_point": {
            "index": "0x1",
            "tx_hash": "0x8ed481459e4d5906b2089d2b516c30b369fd3af5ebc1cded93dd17d28db1f73b"
          }
        },
        {
          "dep_type": "dep_group",
          "out_point": {
            "index": "0x0",
            "tx_hash": "0xf8de3bb47d055cdf460d93a2a6e1b05f7432f9777c8c474abf4eec1d4aee5d37"
          }
        }
      ],
      "hash": "0xb2ad556c3539eecf94c5231abbe19664bf24b18c7170b10d95033f1522d80d74",
      "header_deps": [],
      "inputs": [
        {
          "previous_output": {
            "index": "0x0",
            "tx_hash": "0xc7d90668e58c2252545cf06cbd760a2281da92432a541596a689f02d379b7826"
          },
          "since": "0x0"
        },
        {
          "previous_output": {
            "index": "0x1",
            "tx_hash": "0xfae7c29232265063da649242ce382cff662738354d1258aa8712acfe5e742f49"
          },
          "since": "0x0"
        }
      ],
      "outputs": [
        {
          "capacity": "0xa4a867a00",
          "lock": {
            "args": "0xce5d9dfb0aa6e080a26be07a3cc7772d01b15882",
            "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
            "hash_type": "type"
          },
          "type": {
            "args": "0x1c483ff12bb834ed5607d22b17b3d1e7fbb43dfb8997c12cc7b4643db181ca40",
            "code_hash": "0xf03989dd98974d7a6cbe0a73cdbc4b4839a048a120f6cffd73db935b73c357a5",
            "hash_type": "type"
          }
        },
        {
          "capacity": "0x829b5c636fc",
          "lock": {
            "args": "0xce5d9dfb0aa6e080a26be07a3cc7772d01b15882",
            "code_hash": "0x9bd7e06f3ecf4be0f2fcd2188b23f1b9fcc88e5d4b65a8637b17723bbda3cce8",
            "hash_type": "type"
          },
          "type": null
        }
      ],
      "outputs_data": [
        "0x4f7261636c6543656c6c32010000080000002a0100000c0000009b0000008f00000018000000200000004000000041000000490000000400000057425443cdc9073cbe050000000000000000000000000000000000000000000000000000080dda381592010000420000003078636331346162613034663062303361356466356566326363326131363366663334633335383633666264363563643133376165646530666234303334366636368f00000018000000200000004000000041000000490000000400000057434b42f76b180000000000000000000000000000000000000000000000000000000000080dda38159201000042000000307831373261663738313730353530656430383633383738656132623130396662616364333961666133326533306639666266353665313331336439623263613063",
        "0x"
      ],
      "version": "0x0",
      "witnesses": [
        "0x5500000010000000550000005500000041000000284be4b5f8f6530048e71b96d8becf64dd5c23873f59027a88ec13ca57912c607f909dbfa59b74d1955c8dab415f872f7cbd4a4b659af1bd059fa8184259179b00"
      ]
    },
    "tx_status": {
      "block_hash": null,
      "block_number": null,
      "reason": null,
      "status": "pending",
      "tx_index": null
    }
  },
  "id": 1
}
```
